[package]
name = "ergo-rest"
version = "0.1.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "Ergo node REST API library"
repository = "https://github.com/ergoplatform/sigma-rust"
exclude = [
    "proptest-regressions/*"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bounded-integer = { version = "^0.5", features = ["types"] }
bounded-vec = { version = "^0.5.0", features=["serde"] }
sigma-ser = { version = "^0.4.0", path = "../sigma-ser" }
sigma-util = { version = "^0.4.0", path = "../sigma-util" }
ergo-chain-types = { version = "^0.2.0", path = "../ergo-chain-types" }
ergo-nipopow = { version = "^0.2.0", path = "../ergo-nipopow" }
futures = "0.3"
thiserror = "1"
derive_more = "0.99"
proptest-derive = {version = "0.3.0", optional = true }
reqwest = { package = "reqwest-wrap", version = "0.11.10", path = "../reqwest-wrap" }
serde = { version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", optional = true }
url = "2.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

[dependencies.proptest]
# wasm support, via https://altsysrq.github.io/proptest-book/proptest/wasm.html
version = "1.0.0"
# The default feature set includes things like process forking which are not
# supported in Web Assembly.
default-features = false
# Enable using the `std` crate.
features = ["std"]
optional = true

[features]
arbitrary = ["proptest", "proptest-derive"]

[dev-dependencies]
sigma-test-util = { version = "^0.3.0", path = "../sigma-test-util" }
